### ISSUE TITLE
[Feature request] @Mention option

### ISSUE THREAD

**Issue by kevnm67** [mergeability/mergeable#128]
What are your thoughts on adding the option to @Mention a list of github users?
Maybe something similar to:
```yaml
comments:
  mention-users: [ user1, user2 ]
  message: 'FYI...'
```

**Comment by jusx** [comment]
@kevnm67 We are working on this feature. Right now when the validation of mergeability fails, mergeable will automatically create a check. In the near future you will be able to specify a list of actions like `comment`, `check`, etc  to be performed when validation fails or pass on a pull_request or issue. 

This way you can specify any action(s) to be performed when validation fails or passes.

The configuration format will change but we've made it backward compatible with v1 config format.

**Comment by kevnm67** [comment]
@jusx Sounds great!

**Comment by shine2lay** [comment]
Hey @kevnm67 , it seems you can just add mentions directly in the payload and it will work. Here is an config i tested :
```
- do: comment
        payload:
          body: >
            @shine2lay mention test
```
Is this the feature you had in mind?
