### ISSUE TITLE
Exclude approval requirement for certain PRs

### ISSUE THREAD

**Issue by roblabla** [mergeability/mergeable#145]
It'd be nice if we could remove the requirement for approvals for certain PRs. In particular, I'd be interesting in making PRs created by dependabot to not require approvals. This could be done based on a label, e.g.

```yaml
mergeable:
  pull_requests:
    approvals:
      min: 5
      except:
         label: dependencies
```

If this is something that would be accepted, I can work on a PR to implement it.

**EDIT**:

Actually, I see there's an undocumented `and`/`or` operator that could be used to implement this. Then all that'd be needed is adding a 'label' rule to processFilters.

```yaml
mergeable:
  pull_requests:
    approvals:
      or:
        - min: 5
        - label: '^dependencies$'
```

**Comment by jusx** [comment]
Hey @roblabla, interesting use case. We'd be happy to accept your PR. I do think that the configuration can be like so:

```yml
mergeable:
  pull_requests:
    approvals:
       min: 5
       label: '^dependencies$'
```

It is an implied `OR`. I'm also totally OK with what you've already implemented in your fork.

### FYI
We have been working on re-factoring the underlying architecture of mergeable so that it's a lot more flexible and modular. Please take a look at: https://github.com/jusx/mergeable/tree/flex -- it is currently in the e2e testing phase. Making sure that everything works properly before merging into master and deploying. We've found and fixed a few bugs but am getting close to finalizing a release. Hopefully end of the week or next.

It does have a new configuration format and the above config will transform automatically as will any old (v.1.0.0) config format. You could:

1. Do a PR against `master` and one against the `flex` branch. Once merged to master, it auto-deploys. We'd be happy to port your code over to `flex` for you though.
**or**
2. Just do a PR against `flex` and wait for the release.

With the new architecture, ideally it would be:
```yml
- do: approvals
  min:
    count: 2 # Number of minimum reviewers. In this case 2.
  unless: 
    - do: label
      must_include:
        regex: dependent
```  

In the above example, I'm using `unless` instead of `except` since in python the `except` keyword is used in a `try`...`except` block for catching errors.

**Note:** We have not implemented `unless` yet and it's something I just thought off as a possibility to cater to these kinds of use cases and re-use the validators in a modular and pluggable way.
