### ISSUE TITLE
Automatically remove obsolete comments by mergeable

### ISSUE THREAD

**Issue by cornelius** [mergeability/mergeable#157]
When mergeable comments on an issue because a validation fails it adds all the information why. That's helpful. But when the issue is fixed, e.g. by adding a label and a description, the comment stays. That can be quite confusing and it also adds some noise to the issue.

It would be great if mergeable would remove its own comment if it doesn't apply anymore.

This would also prevent multiple mergeable comments in a row, when an issue is edited and mergeable is triggered by each part of the edit.

Example: Add an issue without description and label, mergeable comments, add a label, mergeable comments again, add a description, no further comment, but the two comments which are there now, don't apply anymore.

**Comment by jusx** [comment]
Hi @cornelius, thank you for creating this issue. Quick question, let's say you configured your recipe to only trigger on `issues.opened` will that be good enough? This way it will be less noise. 

And perhaps only configure mergeable to comment on `pass` when `issues.edited` with a success message.

Will that work better?

**Comment by cornelius** [comment]
Hi @jusx, I wasn't aware that you could use triggers in the configuration. Let me try that and see if that works better.

Is there a changelog or something like that where I could learn about these kind of changes?

**Comment by jusx** [comment]
@cornelius We don't have a changelog per-se. We do [publish releases in GH](https://github.com/jusx/mergeable/releases) that is being used like a changelog. I will be publishing a release for each [milestone](https://github.com/jusx/mergeable/milestones) reached.

Were you able to get it working as per my suggestion? Here's what the config might look like:
```yml
version: 2
mergeable:
  - when: issues.opened
    validate:
    - do: title
      must_include:
        regex: ^(feat|bug)
    fail:
      - do: comment
        payload:
          body: Title must begin with feat or bug.
  - when: issues.edited
    validate:
    - do: title
      must_include:
        regex: ^(feat|bug)
    pass:
      - do: comment
        payload:
          body: All Good!
```

**Comment by cornelius** [comment]
Thanks for the example. I tried a similar configuration. Only commenting on issues when the issue is created works nicely.

Commenting on when the validation passes has a problem, though, because this comments on each change. So when I fix the title to pass the validation there is an "All Good!" comment but when I modify the title later in a way that it still passes the validation, there is another "All Good!" comment again. So once the issue is in a good shape from mergeable's point of view it adds a comment on each change resulting in multiple "All Good!" comments in the issue.

It looks like without keeping track of the validation state in some way it's hard to reduce the noise by repeating comments on issues.

**Comment by shine2lay** [comment]
@cornelius that is a good point, one solution i can think of is add a new option to check if the last comment in the issue is created by mergeable and only create an issue with `All Good!` if that is true.
example config could be something like:
```
do: 'comment'
iff: 
  exists: 'comment'
    from: 'mergeable-bot'
    last: true
```
Do you think this is an good solution for your needs? 
keeping track of validation states will require a lot more work as we aren't currently storing any data at all.

**Comment by shine2lay** [comment]
Or another solution could be to check if there exists a comment from mergeable, where body contains something.
```
do: 'comment'
iff: 
  exists: 'comment'
    from: 'mergeable-bot'
    body:
      must_include: 'fail'
```
