### ISSUE TITLE
Dependent validator should support OR & AND operators

### ISSUE THREAD

**Issue by jusx** [mergeability/mergeable#191]
The [dependent](https://github.com/jusx/mergeable#dependent) validator should support [OR and AND operators](https://github.com/jusx/mergeable#advanced-logic).

Consider the following for a repo with both Rails and Node:

```yml
- do: dependent
  or: 
    - changed:
      file: package.json
      files: ['package-lock.json', 'yarn.lock']
    - changed:    
      file: “Gemfile”
      files:  ["Gemfile.lock", "Gemfile_next.lock" ]
```
