### ISSUE TITLE
Merge on green label

### ISSUE THREAD

**Issue by kevnm67** [mergeability/mergeable#201]
**Context**

Waiting on status checks or an author to respond to a PR approval can increase the time to merge.  One solution is automating the merge process using labels or PR comments.

Pseudo label example:
```yml
- do: merge
  labels: 'merge on green', 'merge when passing'
  type: squash #options: merge, squash, rebase
  delete_branch: true # deletes the branch once merged.
  delay: 30 # Wait 30 sec. before performing merge.
```

or, using the comment approach:
```
@mergable-bot merge on green
```

Other bot examples:
- [Ranger](https://github.com/marketplace/ranger)
- [Mergify](https://github.com/marketplace/mergify)
