### ISSUE TITLE
Mergeable not passing after approval/todos

### ISSUE THREAD

**Issue by dorongutman** [mergeability/mergeable#208]
I have the following .mergable file:
```YAML
version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: title
        must_exclude:
          regex: \bWIP|wip\b
          message: WIP cannot appear in the title.
      - do: description
        must_exclude:
          regex: \[ \]
          message: There are incomplete TODO task(s) unchecked.
      - do: approvals
        min:
          count: 1
```

When a pull request is created and the description doesn't have the todo list items checked (it gets prepopulated by a github template file), mergeable fails. However, if the user clicks the checkboxes it doesn't rerun mergeable to pass the check, only after I manually re-queue it.
Same thing happens with approvals - after the reviewer approves the pull request, mergeable doesn't mark the check as passed, only after I manually re-queue it.

I do see the webhook coming into the mergeable heroku app in the logs, but mergeable isn't showing as though it ran.
