### ISSUE TITLE
Checks fails when specifying approvals with OR in the configuration with 1 approved

### ISSUE THREAD

**Issue by droshev** [mergeability/mergeable#222]
## To Reproduce
1. Create a recipe like this:
```
version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: approvals
        or: 
          - required:
            reviewers: [ 'saad-mo' ] 
          - required:
            reviewers: [ 'InnaAtanasova' ] 
```
2. open a PR
link to our [PR](https://github.com/SAP/fundamental/pull/1520)

## Actual
The Mergeable check in the PR fails.
```
❌ Validator: APPROVALS
❌ ()
Input : InnaAtanasova
Settings : {"or":[{"required":null,"reviewers":["saad-mo"]},{"required":null,"reviewers":["InnaAtanasova"]}]}
```

## Expected
The Mergeable check should validate and complete appropriately.

similar issue https://github.com/mergeability/mergeable/issues/171

**Comment by shine2lay** [comment]
@droshev Hi, just from reading the config file you shared, i think 'reviewers' needs to be indented, from the output you shared, 'reviewers' are not being recognized by the bot.
```
version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: approvals
        or: 
          - required:
              reviewers: [ 'saad-mo' ] 
          - required:
              reviewers: [ 'InnaAtanasova' ] 
```
