### ISSUE TITLE
No error feedback when validate.do has an invalid key

### ISSUE THREAD

**Issue by denis-sokolov** [mergeability/mergeable#224]
If a `validate.do` key includes an invalid value, Mergeable silently does not do anything. It does not report red, yellow, or green at all.

If I set invalid version, Mergeable nicely reports “Invalid configuration”.

If I use `mussst_exclude` instead of `must_exclude`, Mergeable reports this is not supported.

So this is specific to `validate.do` key.

Minimally similar to #154.

This config triggers Mergeable correctly:

```yml
version: 2
mergeable:
  - when: pull_request.opened, pull_request.edited, pull_request.synchronize
    validate:
      - do: description
        must_exclude:
          regex: 'DO NOT MERGE|WIP'
```

Here I changed `description` to `thing` by mistake and Mergeable is silent:

```yml
version: 2
mergeable:
  - when: pull_request.opened, pull_request.edited, pull_request.synchronize
    validate:
      - do: thing
        must_exclude:
          regex: 'DO NOT MERGE|WIP'
```
