### ISSUE TITLE
Check never finishes

### ISSUE THREAD

**Issue by tiferrei** [mergeability/mergeable#233]
Hi my check seems to never finish if I add comment actions.
Here's my config:
```yaml
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        must_exclude:
          regex: ^WIP
      - do: label
        must_exclude:
          regex: WIP|wip|work-in-progress
        must_include:
          regex: deploy|DEPLOY
    fail:
      - do: comment
        payload:
          body: >
            **PR Validation Failed**: DEPLOY has not been acknowledge or PR in WIP. Please add the DEPLOY label and remove WIPs.
    pass:
      - do: comment
        payload:
          body: >
            **PR Validation Passed**: DEPLOY acknowledge. Can now merge.
```
It gets to comment the pass/fails, but the check never finishes running.
