### ISSUE TITLE
project validation doesn't work

### ISSUE THREAD

**Issue by amalucelli** [mergeability/mergeable#237]
Hi,

I'm trying to configure a project validation using the offical app, but whenever I put the following statement on the configuration file, the check keeps forever on this state "_In progress — Mergeable is running._"

```yaml
version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: project
        no_empty:
          enabled: true
          message: 'Pull request should have a project.'
```

Is there something wrong with this config?

**Comment by andrewbarnesweb** [comment]
I am experiencing the same issue with projects. Have you had luck with other validation?

**Comment by shine2lay** [comment]
@andrewbarnesweb I wasn't able to find any error in logs, i'll dig into a bit more later today. Do you have a link to repo where this is failing?

**Comment by shine2lay** [comment]
@amalucelli @andrewbarnesweb I copy pasted the config provided and mergeable ran successfully. link[https://github.com/shine2lay/MergeableTest/pull/51] 
see screenshot: 
![image](https://user-images.githubusercontent.com/5243508/75799698-4756be00-5d2d-11ea-8693-aa756fbeb4bb.png)

**Comment by andrewbarnesweb** [comment]
It’s a private repo I’m afraid. I’ll post the latest config we’re trying. 

```yml
version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: project
        must_include:
          match: March 2020
          message: PR must be in a sprint project to be merged.
```

**Comment by shine2lay** [comment]
@andrewbarnesweb i found the issue. please use `regex` instead of `match`. It seems there is a minor bug with the `error` message and ReadMe is misleading for this project. 
```
version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: project
        must_include:
          regex: March 2020
          message: PR must be in a sprint project to be merged.
```
