### ISSUE TITLE
Dependent validator should support globes

### ISSUE THREAD

**Issue by pkuczynski** [mergeability/mergeable#246]
The dependent validator should support globes. So I can define when one of the files matching glob pattern is part of PR, the other file should be too. Have a look at the following example:

```
- do: dependent
   changed:
      file: 'src/model/*'
      files: ['docs/api.yaml']
```

Changes to any models (describing my API interface) should be reflected in `api.yaml`.

Possibly the syntax could change a bit to:

```
- do: dependent
   changed:
      files: ['src/model/*']
      require: ['docs/api.yaml']
```

Would that be possible?
