### ISSUE TITLE
Internal error when adding approvals validation

### ISSUE THREAD

**Issue by AFriemann** [mergeability/mergeable#256]
We are seeing an internal server error and getting a notice to open an Issue

### Stacktrace

```
HttpError: Resource not accessible by integration
    at /app/node_modules/@octokit/request/dist-node/index.js:66:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Job.doExecute (/app/node_modules/bottleneck/light.js:405:18)
```

### Our config

```
# https://github.com/mergeability/mergeable
version: 2
mergeable:
  - when: pull_request.*
    validate:
      # validate title
      - do: title
        no_empty:
          enabled: true
        must_include:
          regex: '^\[[A-Z]+-[0-9]+\]'
      # disallow merging when WIP
      - do: label
        must_exclude:
          regex: 'wip'
      - do: approvals
        required:
          owners: true
          assignees: true
```

it works fine for us without the approvals validation, when adding it errors out.

![Screenshot_2020-03-17-mergeable-issue](https://user-images.githubusercontent.com/1730315/76853242-350c7200-684d-11ea-8fc8-6f5d32d7dbeb.png)
