### ISSUE TITLE
possible to display only errors on PR_FAIL?

### ISSUE THREAD

**Issue by iancrowther** [mergeability/mergeable#267]
It appears that the default behaviour for a PR_FAIL is to output all the details for all the validators when a PR fails.

Is it possible to only show the errors?

**Comment by shine2lay** [comment]
hey @iancrowther yes, you can. Give the following config a shot 
```
version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: title
        must_exclude:
          regex: 'test'
      - do: label
        must_include:
          regex: 'test'
    fail:
      - do: checks # default fail case
        status: 'failure' # Can be: success, failure, neutral, cancelled, timed_out, or action_required
        payload:
          title: 'Mergeable Run have been Completed!'
          summary: |
            ### Status: {{toUpperCase validationStatus}}
                 Here are some stats of the run:
                 {{validationCount}} validations were ran.
                 {{passCount}} PASSED
                 {{failCount}} FAILED
          text: "{{#each validationSuites}}\n
                  {{#ifEquals status 'fail'}}\n
                #### {{{statusIcon status}}} Validator: {{toUpperCase name}}\n
                {{#each validations }} * {{{statusIcon status}}} ***{{{ description }}}***\n
                       Input : {{{details.input}}}\n
                       Settings : {{{displaySettings details.settings}}}\n
                       {{/each}}\n
                  {{/ifEquals}}
                {{/each}}
                "
```
