### ISSUE TITLE
Conflicting validators for this repository mergeable configuration?

### ISSUE THREAD

**Issue by rfgamaral** [mergeability/mergeable#276]
This repository own `mergeable.yml` starts with this:

```yml
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        must_exclude:
          regex: ^\[WIP\]
          message: This is work in progress. Do not merge yet.
        must_include:
          regex: ^(feat|docs|chore|fix|refactor|test|style|perf)(\(\w+\))?:.+$
          message: Semantic release conventions must be followed.
```

I'm wondering why is the "must exclude" rule there? I mean, you want conventional commits, that's why you have the "must include" rule, which will fail if you have a PR starting with "[WIP]". So why have this redundant rule? Am I missing something here?
