### ISSUE TITLE
avoid duplication in mergeable config

### ISSUE THREAD

**Issue by shine2lay** [mergeability/mergeable#281]
Currently, each `validators` and `actions` have their own sub options and there is no way to generalize them even if the sub options are the same.

For example: 
```
- when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        must_include:
          regex: '^(build|chore|ci|docs|feat|fix|improvement|perf|refactor|revert|style|test)(\([a-z0-9_-]+\))?: [^\s].+$'
          regex_flag: 'none'
      - do: commit
        messsage:
          regex: '^(build|chore|ci|docs|feat|fix|improvement|perf|refactor|revert|style|test)(\([a-z0-9_-]+\))?: [^\s].+$'
          regex_flag: 'none'
```
It would be nice to have some way to avoid duplication.
For more context, see #241

**Comment by rfgamaral** [comment]
How about something simple like variables (for the regex) and find and replace?

**Comment by shine2lay** [comment]
@rfgamaral that is along the lines of what i am thinking also. 
something like 
```
- when: ***
  global:
    variables: 
      semantic_versioning:
         regex: ' '^(build|chore|ci|docs|feat|fix|improvement|perf|refactor|revert|style|test)(\([a-z0-9_-]+\))?: [^\s].+$'
        regex_flag: 'none'
   validate: 
     - do : title
       must_include: 
          global.semantic_versioning: true
```

**Comment by rfgamaral** [comment]
Wouldn't be simpler to implement a more basic variable system? Similar to Ansible but probably much simpler: https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html

**Comment by shine2lay** [comment]
@rfgamaral oh, this is cool, i didn't know about this. thanks for sharing the link.

**Comment by shine2lay** [comment]
@rfgamaral I did some digging, `yaml` allows you to anchor references in it's specs https://yaml.org/spec/1.2/spec.html#id2785586 . I've tested your config with the anchor and it works out of the box. like this:
```
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        must_include: &regex_semantic
          regex: '^(build|chore|ci|docs|feat|fix|improvement|perf|refactor|revert|style|test)(\([a-z0-9_-]+\))?: [^\s].+$'
          regex_flag: 'none'
      - do: commit
        message: *regex_semantic
      - do: description
        no_empty:
          enabled: true
      - do: label
        must_exclude:
          regex: 'BLOCKED'
          regex_flag: 'none'
      - do: dependent
        changed:
          file: 'package.json'
          files: ['yarn.lock']
```

P.S, you had a typo in `messsage`, i had to fix it for it to work properly
