### ISSUE TITLE
Approvels to kick in on on parts of the source code

### ISSUE THREAD

**Issue by erlichmen** [mergeability/mergeable#283]
We are working with monorepo and I would like that certain parts of the tree will require at least one approval while others don't any way to achive this today?

**Comment by shine2lay** [comment]
hey @erlichmen - Do you mean at the file level ? If so, have you tried `CODEOWNER` file, [here](https://github.com/mergeability/mergeable#approvals)? If this doesn't satisfy your use case, let me know.

Note: `owners` options only works in public repos atm

**Comment by erlichmen** [comment]
we have CODEOWNER but its a private repo.

I was thinking maybe add something like this:

version: 2
mergeable:
  - when: pull_request_review.*, pull_request.*
    validate:
      - do: approvals
        include: packages/** // runs this rule only if there are modified
files in packages
        block:
          changes_requested: true
          message: Please finish all comments in the code review

**Comment by shine2lay** [comment]
If i understand correctly, you should be able to combine `changeset` and `approval` validators.
something like this, this doesn't read `CODEOWNERS` so, it should work for private repo as well

```
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: or
        validate:
          - do: changeset
            must_exlude:
              regex: 'files to skip'
          - do: approvals
              min:
                count: 1
```
