### ISSUE TITLE
Global config isn't working

### ISSUE THREAD

**Issue by kceb** [mergeability/mergeable#293]
For some reason it seems like after I installed the global config that was recently added (via the .github/.github/mergeable.yml file https://github.com/mergeability/mergeable/pull/291), the check momentarily fails then it seems to run again and then pass. Could it be running twice?

I also have multiple checks.

```
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: description
        no_empty:
          enabled: true
        must_include:
          regex: '\[[a-zA-Z]{2,6}-\d{1,7}\]'
          regex_flag: 'none'
          message: >
            Please include ticket link in square brackets (ex: [AAA-123])
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: description
        no_empty:
          enabled: true
        must_include:
          regex: '\[[a-zA-Z]{2,6}-\d{1,7}\]:\shttps:\/\/readyresponders.+'
          regex_flag: 'none'
          message: >
            Automatic linking (via JIRA bot) to the JIRA ticket must occur.
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        no_empty:
          enabled: true
        must_include:
          regex: '\[[a-zA-Z]{2,6}-\d{1,7}\]'
          regex_flag: 'none'
          message: >
            Please include ticket in title in square brackets (ex: [AAA-123])
```

Edit: it _seems_ like having multiple validations doesn't work with the global config. It just takes the last validation

**Comment by shine2lay** [comment]
@kceb hey, yes, this is a known issue with checks (we are only able to create one ATM). We are working on it currently to add this feature #225 which would enable as many different checks as you need.

In the meantime, you should be able to use all the validators in one check for now. 

```
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: description
        no_empty:
          enabled: true
        must_include:
          regex: '\[[a-zA-Z]{2,6}-\d{1,7}\]'
          regex_flag: 'none'
          message: >
            Please include ticket link in square brackets (ex: [AAA-123])
      - do: description
        no_empty:
          enabled: true
        must_include:
          regex: '\[[a-zA-Z]{2,6}-\d{1,7}\]:\shttps:\/\/readyresponders.+'
          regex_flag: 'none'
          message: >
            Automatic linking (via JIRA bot) to the JIRA ticket must occur.
      - do: title
        no_empty:
          enabled: true
        must_include:
          regex: '\[[a-zA-Z]{2,6}-\d{1,7}\]'
          regex_flag: 'none'
          message: >
            Please include ticket in title in square brackets (ex: [AAA-123])
```

**Comment by kceb** [comment]
thanks, @shine2lay previously I tried having two description validations in one check and it didn't work, which led me to just separate my checks. Let me give that a shot, maybe I had a syntax error when I first did it.

**Comment by shine2lay** [comment]
@kceb alternatively, you can use `and` and `or` options as well [here](https://github.com/mergeability/mergeable#advanced-logic)

```
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: description
        no_empty:
          enabled: true
        and: 
          - must_include:
              regex: '\[[a-zA-Z]{2,6}-\d{1,7}\]'
              regex_flag: 'none'
              message: >
                Please include ticket link in square brackets (ex: [AAA-123])
          - must_include:
              regex: '\[[a-zA-Z]{2,6}-\d{1,7}\]:\shttps:\/\/readyresponders.+'
              regex_flag: 'none'
              message: >
                Automatic linking (via JIRA bot) to the JIRA ticket must occur.
      - do: title
        no_empty:
          enabled: true
        must_include:
          regex: '\[[a-zA-Z]{2,6}-\d{1,7}\]'
          regex_flag: 'none'
          message: >
            Please include ticket in title in square brackets (ex: [AAA-123])
```
Note: indent maybe off
