### ISSUE TITLE
Error : UnSupportedSettingError: validator/title: must_include.regex_flag option is not supported

### ISSUE THREAD

**Issue by taylor-cedar** [mergeability/mergeable#310]
This started happening yesterday.  This is the rule
```
version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: title
        must_include:
          regex: '^[A-Z]+-[0-9]+: [A-Z].+'
          regex_flag: 'none' # Case sensitive
          message: 'Title must have the format `<JIRA_TICKET>: <SHORT_DESCRIPTION_SENTENCE_CASE>`. If your PR does not have a ticket, please create one.
```

This setting matches the example in the readme.
```
- do: title
  no_empty:
     enabled: true # Cannot be empty when true. A bit redundant in this case since GitHub don't really allow it. :-)
     message: 'Custom message...'
  must_include:
     regex: 'doc|feat|fix|chore'
     regex_flag: 'none' # Optional. Specify the flag for Regex. default is 'i', to disable default use 'none'
     message: 'Custom message...'
```
