### ISSUE TITLE
Error in pull request size check

### ISSUE THREAD

**Issue by tenshiAMD** [mergeability/mergeable#313]
We have this configuration for a check below:

```
- when: pull_request.*, pull_request_review.*
    name: 'Validate Pull Request Size'
    validate:
      - do: size
        ignore: 
          - '*.lock'
        lines:
          max:
            count: 500
            message: Lines of code have too many changes. It should be under 500 lines of addtions and deletions.

```

its started to failed with this Error Stacktrace below:

```
TypeError: supportedSettings[key].includes is not a function
    at Size.validateSettings (/app/lib/validators/validator.js:84:42)
    at Size.processValidate (/app/lib/validators/validator.js:42:12)
    at validateFuncCall (/app/lib/flex.js:171:74)
    at /app/lib/flex.js:224:21
    at Array.forEach (<anonymous>)
    at createPromises (/app/lib/flex.js:218:18)
    at getValidatorPromises (/app/lib/flex.js:173:10)
    at processWorkflow (/app/lib/flex.js:127:40)
    at async executeMergeable (/app/lib/flex.js:37:3)
    at async /app/lib/mergeable.js:87:7
```

Any ideas what caused this? Thanks in advance for the help~! 🎉
