### ISSUE TITLE
Feature Idea: allow for a "pull_request_review.approved" event alias

### ISSUE THREAD

**Issue by SeanKilleen** [mergeability/mergeable#319]
I have a use case where I'd like to run some mergeable rules only when a pull request is approved (a certain set of labels for additional cleanup, thank you, etc. prior to merge). 

As far as I can tell currently, the pull request review submitted event does have a `state` field, which would be set to `approved` in these instances. so `pull_request_review.approved` would be an alias for `pull_request_review.submitted` or `pull_request_review.edited` with a state of `approved`.

For now we'll do a blunter version based on `pull_request_review.submitted`, but this seemed like something you might find worth considering. 

Thanks for a great tool!

**Comment by shine2lay** [comment]
Hey @SeanKilleen, I am trying to understand better on what sort of use cases would having an alias for `pull_request_review.approved` opened up.

Would this config work for your specific use case? If not, can you elaborate on why not?
```
mergeable:
- when: pull_request_review.submitted, pull_request_review.edited
  validate:
    - do: approvals
      min: 
        count: 1
  pass: 'do some action'
```
