### ISSUE TITLE
Unexpected error occurred: `You must pass a string or Handlebars AST to Handlebars.compile. You passed undefined`

### ISSUE THREAD

**Issue by tenshiAMD** [mergeability/mergeable#335]
Greetings to the team! We've suddenly encountered an unexpected error. Kindly see the error details and configuration below:

```
Error Details

Error: You must pass a string or Handlebars AST to Handlebars.compile. You passed undefined
```

Configuration:
```
defaults:
  checks_failure_payload: &checks_failure_payload
    title: 'Mergeable Run have been Completed!'
    summary: |
          ### Status: {{toUpperCase validationStatus}}
              Here are some stats of the run:
              {{validationCount}} validations were ran.
              {{passCount}} PASSED
              {{failCount}} FAILED
    text: "{{#each validationSuites}}\n
          #### {{{statusIcon status}}} Validator: {{toUpperCase name}}\n
          {{#each validations }} * {{{statusIcon status}}} ***{{{ description }}}***\n
                  Input : {{{details.input}}}\n
                  Settings : {{{displaySettings details.settings}}}\n
                  {{/each}}\n
          {{/each}}"

version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Validate Pull Request Description'
    validate:
      - do: description
        no_empty:
          enabled: true
          message: Description is necessary and should not be empty. Kindly provide details with **what** was changed, **why** it was changed, and **how** it was changed.
    fail:
      - do: checks
        status: 'failure'
        payload: *checks_failure_payload
      - do: comment
        payload:
          body: Description is necessary and should not be empty. Kindly provide details with **what** was changed, **why** it was changed, and **how** it was changed.
  - when: pull_request.*, pull_request_review.*
    name: 'Validate Pull Request Title'
    validate:
      - do: title
        no_empty:
          enabled: true
    fail:
      - do: checks
        status: 'failure'
        payload: *checks_failure_payload
      - do: comment
        payload:
          body: Title is necessary and should not be empty. 
  - when: pull_request.*, pull_request_review.*
    name: 'Validate Pull Request Size'
    validate:
      - do: size
        ignore: 
          - '*.lock'
        lines:
          max:
            count: 500
            message: Lines of code have too many changes. It should be under 500 lines of addtions and deletions.
    fail:
      - do: checks
        status: 'failure'
        payload: *checks_failure_payload
      - do: comment
        payload: Lines of code have too many changes. It should be under 500 lines of addtions and deletions.
  - when: pull_request.*, pull_request_review.*
    name: 'Validate Pull Request has one or more assignees'
    validate:
      - do: assignee
        min:
          count: 1
    fail:
      - do: checks
        status: 'failure'
        payload: *checks_failure_payload
      - do: comment
        payload: One or more assignees are required. Kindly add one or more assignees for this pull request.
  - when: pull_request.*, pull_request_review.*
    name: 'Ensure Pull Request has been approved'
    validate:
      - do: approvals
        min:
          count: 1
  - when: pull_request.*, pull_request_review.*
    name: 'Restrict Pull Request as Work in Progress'
    validate:
      - do: label
        must_exclude:
          regex: 'wip'
      - do: title
        must_exclude:
          regex: ^\[WIP\]
```

What could be the issue? Let us know so we can fix it immediately. Thank you and more power to the team.
