### ISSUE TITLE
Mergeable is not picking my config

### ISSUE THREAD

**Issue by pkuczynski** [mergeability/mergeable#341]
Hi, I am using mergeable on the main repo https://github.com/rvm/rvm and it works fine, but for whatever reason, the config is not picked up on the other repo in this org https://github.com/rvm/rvm1-ansible. Can you help me, please?

**Comment by shine2lay** [comment]
Hey @pkuczynski , our logs pick up events from https://github.com/rvm/rvm1-ansible and the 'assign' action seems to be triggering properly. After looking at your config, it doesn't seem to have `checks` action in it. Are you expecting checks to be created? 

If so, you'll have to pass in `checks` action, see below
```
defaults:
  checks_failure_payload: &checks_failure_payload
    title: 'Mergeable Run have been Completed!'
    summary: |
      ### Status: {{toUpperCase validationStatus}}
          Here are some stats of the run:
          {{validationCount}} validations were ran.
          {{passCount}} PASSED
          {{failCount}} FAILED
    text: "{{#each validationSuites}}\n
          #### {{{statusIcon status}}} Validator: {{toUpperCase name}}\n
          {{#each validations }} * {{{statusIcon status}}} ***{{{ description }}}***\n
                  Input : {{{details.input}}}\n
                  Settings : {{{displaySettings details.settings}}}\n
                  {{/each}}\n
          {{/each}}"

version: 2
mergeable:
  - when: pull_request.*
    name: "triage"
    validate:
      - do: label
        and:
          - no_empty:
              enabled: true
          - must_exclude:
              regex: duplicate|feedback|invalid|wont|progress
      - do: assignee
        min:
          count: 1
      - do: description
        no_empty:
          enabled: true
          message: Description should not be empty. Provide details with **what** was changed, **why** it was changed, and **how** it was changed.
      - do: dependent
        changed:
          file: '*'
          files: ['CHANGELOG.md']
        message: Missing CHANGELOG entry
    fail:
      - do: assign
        assignees: [ '@author' ]
      - do: checks
        status: 'failure'
        payload: *checks_failure_payload

  # Stale PR
  - when: schedule.repository
    validate:
      - do: stale
        days: 20
        type: pull_request, issues
    pass:
      - do: comment
        payload:
          body: There was no activity for 20 days. Is this still relevant 
```

If you want further clarity on what's going on, here is the logic implemented:
1. If no action is provided in either `pass`, `fail` or `error` , add `checks` as default (to be backward compatible)
2. If only actions other than `checks` is provided, don't add `check` as default (to support cases where checks are not wanted)
3. If `checks` is a part of the actions provided, all `pass` , `fail` and `error` cases have checks (to prevent case where a check is hanged and never finish processing) 

I hope this help. :smile:
