### ISSUE TITLE
enforce stricter rules on certain branches

### ISSUE THREAD

**Issue by epDHowwD** [mergeability/mergeable#343]
Would it be possible to use the app to enforce stricter rules for PRs targeting a limited set of base branches, e.g. `release` branch. Here I would like to enforce additional rules like title style for automated changelog generation, just as an example. Other branches, like `master` or `develop` might have less strict rules.

I am thinking of something like this:
``` yaml
  - when: pull_request.*, pull_request_review.*
    filter:
      - base: ['release']
```
