### ISSUE TITLE
Can't assign certain authors?

### ISSUE THREAD

**Issue by bobjacobsen** [mergeability/mergeable#359]
We'd like to automatically assign a PR author to the PR. (Yes, this is an odd way to use assignments, but it helps with some of our tools). We use this in the mergeable.yml:
```
version: 2
mergeable: # see https://github.com/mergeability/mergeable
  - when: pull_request.opened
    name: 'Attempt to assign author'
    validate:
      - do: assignee
        min:
          count: 1 # Should be assigned to somebody; if not, assign author
    pass:
      - do: checks
        status: 'success'
    fail:
      - do: assign
        assignees: [ '@author' ] 
      - do: checks
        status: 'success' # Supply the default actions, as if this passed.
        payload:
          title: 'Author assigned'
```

That works fine with the `@author` is a member of the project, but it doesn't assign authors who are not already members of the project.  We then have to do that manually via the GitHub web page for the PR.

Not sure if this is a mergeability issue or something inherent in the GitHub interfaces.  

Any suggestions of where to look to (start to) debug this?  Thanks
