### ISSUE TITLE
Multiple labels on specific branch

### ISSUE THREAD

**Issue by baeharam** [mergeability/mergeable#369]
I want to check mergeability when PR is opening to `master` branch. To be merge, it needs two labels `qa passed` and `develop deployed`. However, I couldn't find any configuration guidelines for these issues. How can I do this?

My configuration

```yml
version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: label
        must_include:
          regex: ??
```

I wrote `regex` as `(qa passed)|(develop deployed)`, but it only tests one of them. But, I needs both of them. Also, as said above, this check must be only on `master` branch. Are there solutions?

**Comment by shine2lay** [comment]
@baeharam hey, sorry for the late reply. 
Re branch: unfortunately, we haven't implemented the ability to run mergeable on specific branch yet, we have a ticket to track it #343 . 
Re multiple labels: try the following recipe

```
version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: label
        and:
          - must_include:
              regex: 'qa passed'
          - must_include:
              regex: 'develop deployed'
```
