### ISSUE TITLE
I don't understand why this commit validator is failing

### ISSUE THREAD

**Issue by rfgamaral** [mergeability/mergeable#391]
For my [rfgamaral/eslint-config-typescript-unified](https://github.com/rfgamaral/eslint-config-typescript-unified/blob/master/.github/mergeable.yml) project I have the following `mergeable.yml` configuration:

```yml
version: 2

mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        must_include: &regex_conventional_commits
          regex: '^(build|chore|ci|docs|feat|fix|improvement|perf|refactor|revert|style|test)(\([a-z0-9_-]+\))?: [^\s].+$'
          regex_flag: 'none'
      - do: commit
        message: *regex_conventional_commits
      - do: description
        no_empty:
          enabled: true
      - do: label
        must_exclude:
          regex: 'BLOCKED'
          regex_flag: 'none'
      - do: dependent
        changed:
          file: 'package.json'
          files: ['yarn.lock']
```

And some PRs created by dependabot end up failing, example: https://github.com/rfgamaral/eslint-config-typescript-unified/pull/210/checks?check_run_id=1105479929

I must be blind because I can't figure out where's the mistake, can you help me out, please?
