### ISSUE TITLE
Source branch name validation missing

### ISSUE THREAD

**Issue by szymonrychu** [mergeability/mergeable#424]
I really really need to check source branch name in a pull request.
Something like `baseRef` but for the branch names that the merge request is based on to ensure compatibility with other systems/integrations like Jira.

Example of config:
```
version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: ref
        must_include:
          regex: '^(feature|hotfix)\/.+$'
          message: |
            Your pull request doesn't adhere to the branch naming convention described <a href="some link">there</a>!'
```
Based on provided example branch named `feature/something` or `hotfix/XD-123` will be passing.
Branch named simply `xd` will fail with verbose description on why and how to improve the MR.

**Comment by szymonrychu** [comment]
Right now I need to use custom github action to have this functionality:
```
name: branch-name-check

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: mshick/add-pr-comment@v1
      with:
        message: |
          Your pull request doesn't adhere to the convention described <a href="some link">there</a>!
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
        allow-repeats: true # This is the default
    - name: 'Fail on wrong branch name!'
      if: github.ref != 'refs/heads/feature/.*' && github.ref != 'refs/heads/hotfix/.*'
      run: |
        exit 1
```
