### ISSUE TITLE
baseRef validator raising internal error

### ISSUE THREAD

**Issue by moltob** [mergeability/mergeable#428]
I am trying to use the new `baseRef` validator to restrict certain validations to specific PR base branches.

This is my config:

```yaml
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:

      - do: or
        validate:
          - do: baseRef
            must_exclude: ^master$
          - do: approvals
            required: {reviewers: [user1]}
          - do: approvals
            required: {reviewers: [user2]}

      - do: or
        validate:
          - do: baseRef
            must_exclude: ^master-mike$
          - do: approvals
            required: {reviewers: [user3]}
```

I might have screwed up the config syntax in some way, but the error raised by the Github app is:

> ❗ Validator: INTERNAL ERROR
> Status ERROR

> ❗ Internal error!
> Input :
> Settings : {}
> Error : This is a mergeable bug, please report it on our issue tracker: https://github.com/mergeability/mergeable/issues/new

with this call stack:

```
TypeError: supportedSettings[key].includes is not a function
    at BaseRef.validateSettings (/opt/app-root/src/lib/validators/validator.js:84:42)
    at BaseRef.processValidate (/opt/app-root/src/lib/validators/validator.js:42:12)
    at validateFuncCall (/opt/app-root/src/lib/flex/lib/getValidatorPromises.js:4:74)
    at arrayToIterate.forEach.element (/opt/app-root/src/lib/flex/lib/createPromises.js:9:21)
    at Array.forEach (<anonymous>)
    at createPromises (/opt/app-root/src/lib/flex/lib/createPromises.js:3:18)
    at getValidatorPromises (/opt/app-root/src/lib/flex/lib/getValidatorPromises.js:6:10)
    at andOrValidatorProcessor (/opt/app-root/src/lib/validators/lib/andOrValidatorProcessor.js:43:20)
    at Or.validate (/opt/app-root/src/lib/validators/or.js:17:12)
    at Or.processValidate (/opt/app-root/src/lib/validators/validator.js:53:17)
    at validateFuncCall (/opt/app-root/src/lib/flex/lib/getValidatorPromises.js:4:74)
    at arrayToIterate.forEach.element (/opt/app-root/src/lib/flex/lib/createPromises.js:9:21)
    at Array.forEach (<anonymous>)
    at createPromises (/opt/app-root/src/lib/flex/lib/createPromises.js:3:18)
    at getValidatorPromises (/opt/app-root/src/lib/flex/lib/getValidatorPromises.js:6:10)
    at processWorkflow (/opt/app-root/src/lib/flex/lib/processWorkflow.js:42:40)
    at <anonymous>
```

Please note this is occuring on a Github Enterprise installation using the current HEAD of mergeable.

**Comment by shine2lay** [comment]
hey @moltob, from a first glance, I think your config is missing `regex: ` for `must_exclude`

https://mergeable.readthedocs.io/en/latest/validators/baseRef.html?highlight=baseRef

I believe it should be something like this. (indent maybe off since I can't tab in GH)
```
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:

      - do: or
        validate:
          - do: baseRef
            must_exclude: 
              regex: ^master$
          - do: approvals
            required: {reviewers: [user1]}
          - do: approvals
            required: {reviewers: [user2]}

      - do: or
        validate:
          - do: baseRef
            must_exclude: 
              regex: ^master-mike$
          - do: approvals
            required: {reviewers: [user3]} 
```
