### ISSUE TITLE
Pull requests are getting merged even when validation is present

### ISSUE THREAD

**Issue by MiroslavCsonka** [mergeability/mergeable#431]
I've quickly read the docs, threw together 2 snippets from recipes and I ended up with:
```
version: 2		
 mergeable:		
   - when: pull_request.*, pull_request_review.*, status.*, check_suite.*		
     name: "Automatically merge pull requests once it passes all checks"		
     validate:		
       - do: label		
         and:		
           - must_include:		
               regex: 'merge-on-green'		
           - no_empty:		
               enabled: true		
               message: 'Must have some tags'		
     pass:		
       - do: merge		
         merge_method: "squash"
```

But for some reason, all of my PRs are getting merged. An I using the no_empty validation wrong?

My initial build looked like:
```
version: 2
 mergeable:
   - when: pull_request.*, pull_request_review.*, status.*, check_suite.*
     name: "Automatically merge pull requests once it passes all checks"
     validate:
       - do: label
         must_include:
           regex: merge-on-green
     pass:
       - do: merge
         merge_method: "squash"
```
But I even that was passing on empty tags.

What's the correct configuration for merging only PRs that include `merge-on-green` labels and nothing else?

**Comment by shine2lay** [comment]
@MiroslavCsonka hi, from a first glance, it looks okay. Let me try to replicate it later today.

**Comment by samj1912** [comment]
@MiroslavCsonka you need to add branch protections and mandate checks that you want to pass before the PR is merged. Currently if it sees a green button on the PR it will merge it.

**Comment by shine2lay** [comment]
> @MiroslavCsonka you need to add branch protections and mandate checks that you want to pass before the PR is merged. Currently if it sees a green button on the PR it will merge it.

yeah, this makes a lot of sense.

**Comment by MiroslavCsonka** [comment]
We do utilize Github checks and mergeable correctly waits for the CI. It's just that we would like it to be automatically merged **ONLY** when a specific label is present.
<img width="928" alt="image" src="https://user-images.githubusercontent.com/1818208/101151944-49321280-361a-11eb-8e6d-566496d601bc.png">

**Comment by shine2lay** [comment]
@MiroslavCsonka 
I was not able to reproduce it. If you are okay with it, would you mind posting the link to PR where this is occurring?

one potential solution i can think of is to add a `required` checks that will fail when 'merge-on-green' label doesn't exists

Note the indentations may be off
```
version: 2
mergeable:
   - when: pull_request.*, pull_request_review.*, status.*, check_suite.*
     name: "Automatically merge pull requests once it passes all checks"
     validate:
       - do: label
         must_include:
           regex: merge-on-green
     pass:
       - do: merge
         merge_method: "squash"
     fail:
       - do: checks
         status: 'failure'
         payload: 
           title: "Missing 'merge-on-green' label"
```

of course this would mean that you'll have to add this label in order to be able to merge any PR.
