### ISSUE TITLE
 TypeError: supportedSettings[key].includes is not a function

### ISSUE THREAD

**Issue by PoisonousJohn** [mergeability/mergeable#444]
Hi there, I'm getting an error with the following config
```yaml
version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: or
        validate:
          - do: size
            ignore: ["**/*.json"]
            lines:
              max:
                count: 1500
                message: Change is very large. Should be under 1500 lines total
          - do: label
            begins_with: "combined-pr"
```

Am I doing something wrong here?

```
exclamation Validator: INTERNAL ERROR

Status ERROR

    exclamation Internal error!
    Input :
    Settings : {}
    Error : This is a mergeable bug, please report it on our issue tracker: https://github.com/mergeability/mergeable/issues/new

TypeError: supportedSettings[key].includes is not a function
    at Label.validateSettings (/app/lib/validators/validator.js:84:42)
    at Label.processValidate (/app/lib/validators/validator.js:42:12)
    at validateFuncCall (/app/lib/flex/lib/getValidatorPromises.js:4:74)
    at /app/lib/flex/lib/createPromises.js:9:21
    at Array.forEach (<anonymous>)
    at createPromises (/app/lib/flex/lib/createPromises.js:3:18)
    at getValidatorPromises (/app/lib/flex/lib/getValidatorPromises.js:6:10)
    at andOrValidatorProcessor (/app/lib/validators/lib/andOrValidatorProcessor.js:43:20)
    at Or.validate (/app/lib/validators/or.js:17:12)
    at Or.processValidate (/app/lib/validators/validator.js:53:17)
    at validateFuncCall (/app/lib/flex/lib/getValidatorPromises.js:4:74)
    at /app/lib/flex/lib/createPromises.js:9:21
    at Array.forEach (<anonymous>)
    at createPromises (/app/lib/flex/lib/createPromises.js:3:18)
    at getValidatorPromises (/app/lib/flex/lib/getValidatorPromises.js:6:10)
    at processWorkflow (/app/lib/flex/lib/processWorkflow.js:42:40)
    at async executeMergeable (/app/lib/flex/flex.js:35:3)
    at async /app/lib/mergeable.js:87:7

```
