### ISSUE TITLE
Issue validation does not run

### ISSUE THREAD

**Issue by DragosDumitrache** [mergeability/mergeable#449]
Hello. I've been trying to set up mergeable to run on issues and pull requests. PR validations works fine, but no issue validation occurs. Mostly interested in ensuring a project and a milestone are added to an issue, and would expect a label and a comment to be added if the validation fails.

```yaml
- when: issues.*
    validate:
      - do: description
        no_empty:
          enabled: true
          message: A description must be provided
      - do: label
        no_empty:
          enabled: true
          message: At least one label must be provided
      - do: milestone
        no_empty:
          enabled: true
          message: A milestone must be provided
      - do: project
        must_include:
          regex: 'Engineering|Product'
          message: A project must be provided
    fail:
      - do: labels
        labels: ['needs-info']
        mode: 'add'
      - do: comment
        payload:
          body: >
            One or more of following problems were found with this issue:
              - Description is missing
              - At least one label musts be provided
              - One milestone must be provided
              - One project must be provided
_
```
