### ISSUE TITLE
Multiple configuration sections bug

### ISSUE THREAD

**Issue by iammuho** [mergeability/mergeable#459]
Hey,

I've figured out today, if you define multiple sections in the configuration as below, Mergeable checks all of them but results the last one only.

**Example Config:**
```
---
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        must_exclude:
          regex: ^\[WIP\]
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: headRef
        must_include:
          regex: '.+'
          message: 'Your branch name can contain anything'
```

With this configuration, if we have opened a PR with `[WIP]` in title, mergeable will say it's `successful` because last check is branch and branch can be anything. 

To reproduce the bug, place the above configuration file and create a PR with `[WIP]` in title, and you will see mergeable will pass.

**Comment by shine2lay** [comment]
@iammuho if you want to use multiple recipes, you have to name each one in order to create separate checks

```
---
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'check that the PR is not WIP'
    validate:
      - do: title
        must_exclude:
          regex: ^\[WIP\]
  - when: pull_request.*, pull_request_review.*
    name: 'check headRef'
    validate:
      - do: headRef
        must_include:
          regex: '.+'
          message: 'Your branch name can contain anything'
```
