### ISSUE TITLE
Is that possible to limit auto merge to issues with certain labels?

### ISSUE THREAD

**Issue by LeoQuote** [mergeability/mergeable#465]
I'm trying to setup mergeable to merge pr when CI passed and labeled "lgtm" , I tried this https://github.com/LeoQuote/test-repo/blob/master/.github/mergeable.yml but not working as I expected. The pr https://github.com/LeoQuote/test-repo/pull/2 was merged right after CI passed, totally ignored the validate I configured.

**Expected**: auto merge only merge pr labeled `lgtm`

**Actual**: auto merge merges every pr.

mergeable config:

```
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*, status.*, check_suite.*
    name: "Automatically merge pull requests once it passes all checks"
    validate:
      - do: label
        must_include:
          regex: 'lgtm|approved|goodtogo'
          message: 'We need lgtm tag to auto merge'
    pass:
      - do: merge
        merge_method: "squash"
```

I know this can be done by setting another rule enforcing `lgtm` label and set mergeable check as a must. But I want it this way as it does not require every single pr labeled `lgtm`
