### ISSUE TITLE
option to use username list for approval.limit feature

### ISSUE THREAD

**Issue by vsingal-p** [mergeability/mergeable#509]
Sometimes there is a need of adding a single username for the approval validation to a certain repo, whereas a common team is used across repos for restricting core approval to certain group of people.

Currently to achieve the same, we'll have to a create a repo specific team. It just adds an overhead for maintenance of multiple teams.

It would be great if we can have something like following - 
```
validate:
      - do: approvals
        min:
          count: 1
        limit:
          team: [ 'some-common-team-shared-across-repos' ]
          users: ['custom-user-1-for-this-specific-repo', 'custom-user-2-for-this-specific-repo']
```

**Comment by shine2lay** [comment]
@vsingal-p I think that is a great use case!

**Comment by shine2lay** [comment]
@vsingal-p you mentioned limiting the approval from user for only specific repos, would it make more sense to use the add a new `filter` that will only run the validations on when the repo is as specified? 

I was thinking of something like this: 
```
version: 2
mergeable:
  - when: pull_request.*
     filter: // this will check whether the validation should be run
       - do: repository
          name:
            must_include:
              regex: 'specific repo'
    validate:
      - do: approval
         min:
           count: 1
          limit:
            team: [ 'some-common-team-shared-across-repos' ]
            users: ['custom-user-1', 'custom-user-2']
```

**Comment by vsingal-p** [comment]
The above would make sense only if we have a common mergeable.yml at the organisation level
Even in that case, we could be needing different set of users for different repos.

Currently we have a mergeable.yml in the repo where it's needed, so filter won't be of use to us

Thanks for sharing the idea though, the `or-required` is a good combination I could use in some of my use cases. Never looked it that way

**Comment by vsingal-p** [comment]
And thanks for the quick turnaround adding adding the "users" feature 👯

**Comment by vsingal-p** [comment]
One more question, right now if the following validations fail
```
validate:
      - do: approvals
        min:
          count: 1
        limit:
          team: [ 'some-common-team-shared-across-repos' ]
          users: ['user-1', 'user-2]
```

This is the error published in the checks report
```
❌ Validator: APPROVALS
     ❌ approvals count is less than "1"
     Input :
     Settings : {"min":{"count":1}}
```



**Can we make some change so that the following error is published?**
```
❌ Validator: APPROVALS
     ❌ approvals count is less than "1"
     Input :
     Settings : {"min":{"count":1}}

     ❌ Only approvals from following sources are counted.
     Input :
     Settings : {"users":["some-user"], "teams": ["some-git-team"]}
```
