### ISSUE TITLE
Required reviewer approval not taken into account

### ISSUE THREAD

**Issue by soulskill** [mergeability/mergeable#548]
I use the following check for Pull Request contributions which are above a certain LoC (Lines of Code).
Only `user1` 's approval is taken into consideration but not `user2` 's  for a Pull Request marked with label `special` .

Here:
- `user1`, `user2` are GitHub usernames
- `LoC_COUNT_HERE` is any valid Integer

Can anyone share what might be wrong with the following check:

```
  - when: pull_request.*, pull_request_review.*
    name: "Special Pull Request"
    validate:
      - do: or
        validate:
          - do: and
            validate:
              - do: label
                must_include:
                  regex: 'special'
                  message: 'Must be approved by User1 or User2.'
              - do: approvals
                min:
                  count: 1
                  message: 'Must be approved by User1 or User2.'
                required:
                  reviewers: [ user1, user2 ]
          - do: and
            validate:
              - do: label
                must_exclude:
                  regex: 'special'
                  message: 'Special Pull Request'
              - do: size
                ignore: [ "**/*.json", "**/*.md", "**/*.yml", "**/*.yaml", "**/*.properties" ]
                lines:
                  max:
                    count: LoC_COUNT_HERE
                    message: 'This Pull Request is a special one - get it approved from either User1 or User2.'
```

**Comment by shine2lay** [comment]
@soulskill Hey, i noticed one potential issue in your config, 
to get 'Approval from either User1 or User2' use the following config (indentations maybe off). the `required.reviewers` are `and` by default so you have to split them.
```
- do: approvals
  min:
    count: 1
  or:
  - required:
    reviewers: [ user1 ]
  - required:
    reviewers: [ user2 ]
```

After reading your requirements, I think you can potentially remove the `special` label part and still does what you intended it to.
```
 - when: pull_request.*, pull_request_review.*
    name: "Special Pull Request"
    validate:
      - do: or
        validate:
              - do: approvals
                min:
                  count: 1
                or:
                - required:
                  reviewers: [ user1 ]
                - required:
                  reviewers: [ user2 ]
              - do: size
                ignore: [ "**/*.json", "**/*.md", "**/*.yml", "**/*.yaml", "**/*.properties" ]
                lines:
                  max:
                    count: LoC_COUNT_HERE
                    message: 'This Pull Request is a special one - get it approved from either User1 or User2.'
```
