### ISSUE TITLE
No New Typescript Files: Request for Advice

### ISSUE THREAD

**Issue by jaisal1024** [mergeability/mergeable#550]
I am trying to implement a rule that will disallow introducing new javascript files into our codebase. So one should be allowed to add new code to a current javascript file, but disallowed from creating a new javascript file in our code base. 

I looked at using the content and changeset validators but neither provides a way to include only created files and not just modified files. 

I am proposing adding a new flag to content. Something like `createdFilesOnly`. What are the authors thoughts on this use case and solution?

If this works out, I would also love to add the example for others to see :)

**Comment by shine2lay** [comment]
@jaisal1024 hey, sorry for the late reply. 

Yeah, I don't think we currently have a way to only check changeset against added files.
It can be easily added however, you just need to change this one file https://github.com/mergeability/mergeable/blob/master/lib/validators/changeset.js

as for settings, I think
```
files:
  added: true // allow added files in the changeset against validation
  modified: true // allow modified files in the changeset against validation
  deleted: true //  allow deleted files in the changeset against validation
```

I think with this setting, we can mix and match which type of files to filter in/out.

I am busy these days, I'll try to pick up when I have time. If you want to create a PR, I'll do my best to review and merge it in ASAP
