### ISSUE TITLE
Apply filter to only particular validation

### ISSUE THREAD

**Issue by vsingal-p** [mergeability/mergeable#553]
I have a use case where I want to apply `filter` only for a particular validation

```
run validationX
if filter.conditions == true then run validationY
```

Validation X - check if there is atleast 1 review from certain team
Validation Y - if any file is changed in a certain path, then check if PR title starts with "schema"

```
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'PR checks'
    validate:
      - do: approvals
        min:
          count: 1
        limit:
          teams: [ 'some-team' ]
    filter:
      - do: changeset
        must_include:
          regex: src/main/kotlin/some/path/*.kt
    validate:
      - do: title
        begins_with: ['schema:', 'Schema:', 'SCHEMA:']
```

How to achieve this?

**Comment by vsingal-p** [comment]
@shine2lay

**Comment by vsingal-p** [comment]
I tried this

```
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'PR checks'
    validate:
      - do: and
        validate:
          - do: approvals
            min:
              count: 1
            limit:
              teams: [ 'Some team' ]
      - do: and
        filter:
          - do: changeset
            must_include:
              regex: 'src/main/kotlin/some/path/*.kt'
        validate:
          - do: title
            begins_with:
              match: ['schema:', 'Schema:', 'SCHEMA:']
```

But it's ignoring the `filter` section and running second validation agnostic of filter result
