### ISSUE TITLE
Use semantic-release to create a release candidate per master merge

### ISSUE THREAD

**Issue by quike** [mergeability/mergeable#554]
Currently we are stuck on release 2.0.0 https://github.com/mergeability/mergeable/releases but more merges have been created since that version was released. The purpose of continuous integration is to create unique candidates each time a merge hits master (source of truth). 

I suggest the use of semantic-release to create automatic releases per merge, and rely on its automated process to create new semver version and notes. 

https://github.com/semantic-release/semantic-release

```
name: push

on:
  push:
    branches:
      - master

jobs:
...
  release:
      name: Release
      needs: build
      runs-on: ubuntu-18.04
      steps:
        - name: Checkout
          uses: actions/checkout@v2.3.4
        - name: Setup Node.js
          uses: actions/setup-node@v2.1.2
          with:
            node-version: 14
        - name: Release
          env:
            GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
          run: npx semantic-release@17
```

Combined with the unique version per release we could create unique docker images, to be deployed to GH docker registry.
