### ISSUE TITLE
Docs: Add the missing `name` functionality to documentation 

### ISSUE THREAD

**Issue by shine2lay** [mergeability/mergeable#557]
We have already implemented features that allow user to name the checks
note: indents might be off
```
version: 2
mergeable:
  - when: pull_request.*
    name: "check if WIP exists"
    validate:
      - do: title
        must_exclude:
          regex: ^\[WIP\]
      - do: label
        must_exclude:
          regex: 'wip'
  - when: pull_request.*
      name: " check no empty description"
      validate:
        - do: description
          no_empty:
            enabled: true
            message: Description matter and should not be empty. Provide detail with **what** was changed, **why** it was changed, and **how** it was changed.
```
