### ISSUE TITLE
Add validator to check PR number

### ISSUE THREAD

**Issue by vsingal-p** [mergeability/mergeable#559]
I have a use case when I want to skip validation if the PR number matches certain number.
```
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Schema PR title check'
    validate:
      - do: or
        validate:
          - do: issue_number
          - must_include:
              - regex: '1100'
          - do: changeset
            must_exclude:
              regex: 'XXXX'
          - do: and
            validate:
              - do: changeset
                must_include:
                  regex: 'XXX'
              - do: title
                begins_with:
                  match: [ 'schema:', 'Schema:', 'SCHEMA:' ]
```

So basically sometimes I want to skip this check in certain PR. So for that specific case, we can edit the file and update the number and check would pass because it is in `OR` option

Is there any better way?

If no, does it make sense to add such validator?

**Comment by vsingal-p** [comment]
@shine2lay

**Comment by shine2lay** [comment]
I don't think such a validator exist. I think we can definitely add it.
I am trying to understand the use case a bit better. Isn't the issue number
predetermined by the GitHub system? So why do you filter it out by PR
number?

**Comment by vsingal-p** [comment]
For some pull requests, some checks does not make sense due to the nature of changes in them. 

In those cases, one option is to exercise admin rights and mark those checks as `not required`, merge the PR and then make them `required` again.

A simpler way could be to just skip the check if the PR number matches the number (to be updated manually in mergeable.yml as a change in that PR itself)
When I say that out loud, instead of a validator, it should be a `filter`

**Comment by shine2lay** [comment]
Wouldn't filter by label be better for you? Or even the title ? If u don't
want to run mergeable, just tick a label 'dont run mergeable' when creating
PR

**Comment by shine2lay** [comment]
Or, maybe u can create a "success" check, if certain label exist

**Comment by vsingal-p** [comment]
Filter by label seems to be more feasible.

However, can you elaborate on this `maybe u can create a "success" check, if certain label exist` ?

**Comment by shine2lay** [comment]
So, I see an issue with using "filter",
assumptions I am making: Mergeable check is marked as "required" in Github

When you use a filter like "label", mergeable just won't create a check, therefore the PR won't be mergeable since it's a "required" check.
So, the solution I am thinking of is to simply make all check "success" when a label exists. in this case, we can bypass it and still be mergeable

I think in all your recipe, I would add the following
```
- when: ...
  validate:
    do: or
      - check if label exists
    do: // your check
```
