### ISSUE TITLE
Request review actions seems to be not working properly

### ISSUE THREAD

**Issue by tenshiAMD** [mergeability/mergeable#562]
Hi, I've set this configuration however its seems not to be working, what could be wrong with this configuration. Thanks in advance.

```
- when: pull_request.*
  name: 'Validate Pull Request has a reviewer'
  validate:
    - do: approvals
      min:
        count: 1
  fail:
    - do: request_review
      reviewers: [ 'tenshiAMD' ]
```
