### ISSUE TITLE
Allow array of regexes (or strings) for must_include, must_exclude

### ISSUE THREAD

**Issue by bbugh** [mergeability/mergeable#573]
Hi! 👋 This is a great tool!

I've run into a snag, though. I have a list of about 30 exact filenames that need to be matched in a monorepo (configuration, build related things), and doing it all as one regex is very difficult for readability and writability.

https://github.com/mergeability/mergeable/blob/01fd21a8f81e303ee30d660452047601ba2adf3f/lib/validators/contents.js#L21-L30

Changing these to allow an array in `regex` would be really helpful. Adding `match` like `begins_with` and `ends_with` that does an exact match would be even better to avoid accidental matches or having to mark every filename with boundaries.

Thanks!

**Comment by shine2lay** [comment]
@bbugh Hey! 

re `match`: for `begins_with` and `ends_with`, we just convert them to regex to match anyways, I see your point about potentially troublesome regex.

Have you try `and` or `or` option? I think they could be useful for your use case. 
something like this, they can also be nested

```
- do: contents
  and:
    - must_include:
        regex: 'doc/.*'
        message: 'Custom message...'
    - must_include:
        regex: 'changelog.md'
        message: 'Custom message...'
  or:
    - must_include:
        regex: 'package-lock.json'
        message: 'Custom message...'
    - must_include:
        regex: 'yarn.lock'
        message: 'Custom message...'
```
