### ISSUE TITLE
Adding and removing labels in the same pass results in removing the added label

### ISSUE THREAD

**Issue by bbugh** [mergeability/mergeable#576]
Adding and removing labels in one action results in the newly added label being removed immediately, I believe because `deleteLabels` is looking for the issue's labels, but the operations run asynchronously so it's a race condition. 

![image](https://user-images.githubusercontent.com/438465/128570616-edbfc9a7-e04b-4a12-ae8d-a2dab5a7e482.png)

We cannot use `replace` because we have other labels that need to stay. 

## Potential fixes

I'm happy to PR this, and here's a couple of possible options to resolve it. Do you have a preference?

1. If `replace` supported a "replace these labels with these other labels" rather than removing them all, we could use it.
	```yaml
	  - do: labels
	    labels: ["triaged"]
        replace: ["needs triage"]
        mode: "replace"
    ```

2. Change the `labels` action to allow multiple operations at once, so that the app can get a safe list in one batch. This could get the full list of labels first, make adjustments, and then use `setLabels` for the result.
    ```yaml
      - do: labels
        add: ["needs review"]
        delete: ["work in progress"]

      # or: 

      - do: labels
        replace: ["triaged"]
    ```

I think \#2 is best as it has a consistent API, and the `labels` and `type` options could be cleanly deprecated with a warning.

## Reproduction steps

Given this:

```yaml
    pass:
      - do: labels
        labels: ["needs review"]
        mode: "add"
      - do: labels
        labels: ["work in progress"]
        mode: "delete"
```

The result is this, if `work in progress` is not labeled:

![image](https://user-images.githubusercontent.com/438465/128570535-65d5334d-a2c4-44e4-bc44-620b72da2c1b.png)

If it is labeled `work in progress`, it does this:

![image](https://user-images.githubusercontent.com/438465/128570616-edbfc9a7-e04b-4a12-ae8d-a2dab5a7e482.png)

Changing the order of the `labels` operation in the configuration does not change the outcome.
