### ISSUE TITLE
When author of a PR is required as a reviewer, the PR is blocked

### ISSUE THREAD

**Issue by vandac** [mergeability/mergeable#582]
`mergeable:
- when: pull_request.*, pull_request_review.*
  name: '2approvals and 1 plus2'
  validate:
  - do: approvals
    min:
      count: 2
      message: 'We require at least 2 approvals.'
    or:
    - required:
        reviewers: [ plus2reviewer ]`

In the configuration above, we specify that our PRs require at least two approvals and additionally, one approval must be granted by one of the named reviewers.
If there is only one reviewer and the same reviewer is also an author of a given Pull request, the Pull Request is blocked from merging. The author should be removed from the required approvals as the author cannot approve their own PRs.

**Comment by shine2lay** [comment]
@vandac Hi, first of all, your configuration looks off from your description of the use case. 
re author as reviewer: I believe we are already dismissing `author` as a reviewer so if the `author` approve, we just simply don't count it as an approval.

```
 - when: pull_request., pull_request_review.
    name: '2approvals and 1 plus2'
    validate:
    - do: approvals
      and: 
        - min:
          count: 2
          message: 'We require at least 2 approvals.'
        - required:
           reviewers: [ plus2reviewer ]
``` 
(Note the indentation may be off)
This config seems more closely aligned with your use case where you require 2 approval minimum AND one of them must be a named approver.
