### ISSUE TITLE
Changeset includes minimum files of certain regex

### ISSUE THREAD

**Issue by vsingal-p** [mergeability/mergeable#595]
I am trying to implement a check in which I want that if a change is made in certain files, then there should be more than X number of files.

```
- when: pull_request.*, pull_request_review.*
    name: 'Some PR check'
    validate:
      - do: or
        validate:
          - do: changeset
            must_exclude:
              regex: 'src/main/resources/views/([0-9A-Za-z]+/?)+'
          - do: changeset
            must_include:
              regex: 'src/main/resources/views/([0-9A-Za-z]+/?)+'
            min:
              count: 3
```

But the problem is, `min` includes all the changed files in the PR, and not **only the ones** matching the regex. How to achieve that?

**Comment by vsingal-p** [comment]
@shine2lay

**Comment by vsingal-p** [comment]
Or maybe add `all` to `must_include` in changeset. I see that `must_include` option processor supports functionality of `all` already. It's just that input setting of `changeset` does not expose that.

**Comment by shine2lay** [comment]
hey @vsingal-p that may work, i am not quite sure, another solution i can think off the top of my head is to add `limit` option to `changeset` which will limit which file are to be considered similar to [approvals](https://mergeable.readthedocs.io/en/latest/validators/approval.html).

**Comment by vsingal-p** [comment]
```
- when: pull_request.*, pull_request_review.*
    name: 'Some PR check'
    validate:
      - do: or
        validate:
          - do: changeset
            must_exclude:
              regex: 'src/main/resources/views/([0-9A-Za-z]+/?)+'
          - do: changeset
            and:
              - must_include:
                  regex: 'src/main/resources/views/([0-9A-Za-z]+/?)+'
              - must_exclude:
                  regex: '^(src/main/resources/views/([0-9A-Za-z]+/?)+).*'
              - min:
                  count: 2
```

I tried this. So basically pass when no file under a specific directory (or subdirectory) is changed.
Or if a file has been changed (must_include)..then nothing outside the package should match (must_exclude)..and the changeset should be greater than 2 files

**Comment by vsingal-p** [comment]
Using `limit` might get redundant I guess as we would be copy pasting same regex in most cases I can think of

What say, let's give `all` a shot? I can do that in my forked application and get back to you whether it works or not

**Comment by vsingal-p** [comment]
Also I want to perform an action when the second `changeset` option in `or` is fulfilled. Is that possible?
Current doc says that we can have actions on overall success of the check, not it's individual constituents

**Comment by shine2lay** [comment]
> Using `limit` might get redundant I guess as we would be copy pasting same regex in most cases I can think of
> 
> What say, let's give `all` a shot? I can do that in my forked application and get back to you whether it works or not

How would `all` work? can you give a sample config using `all`?


> Also I want to perform an action when the second `changeset` option in `or` is fulfilled. Is that possible? Current doc says that we can have actions on overall success of the check, not it's individual constituents

For now, i think you can have a second recipe that only include the individual constituents you want and have an action for the second recipe.

**Comment by vsingal-p** [comment]
```
- when: pull_request.*, pull_request_review.*
    name: 'Some PR check'
    validate:
      - do: or
        validate:
          - do: changeset
            must_exclude:
              regex: 'src/main/resources/views/([0-9A-Za-z]+/?)+'
          - do: changeset
            must_include:
              regex: 'src/main/resources/views/([0-9A-Za-z]+/?)+'
              all: true
```

This would mean if any change is made in any file under `views` package, then all the files should be from that package only
