### ISSUE TITLE
validation fails on too big description

### ISSUE THREAD

**Issue by laughedelic** [mergeability/mergeable#599]
> HttpError: Invalid request.
>
> Only 65535 characters are allowed; 184898 were supplied.

I have a bot updating description with some logs, so it gets quite big. But the validation I have just checks that it's not empty, so I think it should work on a description of any size.

**Comment by laughedelic** [comment]
Oh, I also had this validation:

```yaml
      - do: description
        # All todo check boxes must be checked.
        must_exclude:
          regex: '- \[ \]'
          message: There are incomplete TODO task(s) unchecked
```

After removing it, `no_empty` works as expected.
