### ISSUE TITLE
Payload cannot be used in Validator like specified in the documentation

### ISSUE THREAD

**Issue by dgteixeira** [mergeability/mergeable#603]
Hello,

When trying to use your recipe for draft PR, mergeable throws an error saying that **validator does not support payload**.

Error on mergeable action
```
Invalid Filters or Validators or Actions
Error: Validators have thrown Error: Cannot find module './validators/payload'
Require stack:

/app/lib/register.js
/app/lib/flex/lib/processWorkflow.js
/app/lib/interceptors/push.js
/app/lib/interceptors/index.js
/app/lib/flex/flex.js
/app/lib/mergeable.js
/app/index.js
/app/node_modules/probot/lib/helpers/resolve-app-function.js
/app/node_modules/probot/lib/run.js
/app/node_modules/probot/lib/index.js
/app/node_modules/probot/lib/bin/probot-run.js
/app/node_modules/probot/bin/probot-run.js
```

Configuration used (retrieved directly from your [documentation](https://mergeable.readthedocs.io/en/latest/recipes.html#only-run-rules-if-pr-is-not-a-draft)):
```
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Draft check'
    validate:
      - do: payload
        pull_request:
          draft:
            boolean:
              match: false
    pass:
      - do: comment
        payload:
          body: This PR is NOT a draft!
    fail:
      - do: comment
        payload:
          body: This PR is STILL a draft!

```
