### ISSUE TITLE
Mergeable Keeps Running

### ISSUE THREAD

**Issue by vaishnav-canarys** [mergeability/mergeable#606]
I am using the following config

```
version: 2
mergeable:
  - when: pull_request.opened
    validate:
      - do: commit
        message:
          regex: 'AB\#[0-9]+'
          message: 'The Azure ticket does not exist'   
    pass:
      - do: checks
        status: 'success'
    fail:
      - do: comment
        payload: 
          body: Add the missing work item id and the corresponding commit in the PR.
```

The mergeable check keeps running and doesn't seem to end.
