### ISSUE TITLE
Tagging new issues with labels based upon regex

### ISSUE THREAD

**Issue by chipzoller** [mergeability/mergeable#609]
Love this project but struggling to find a way on how to assign a tag to a new issue based upon a given string found in the issue body. I'm trying to search for a given Markdown heading and the value thereafter and assign a tag in a 1-to-1 fashion based on that value (ex., find `AKS` assign tag `K8s-AKS`; find `GKE` assign tag `K8s-GKE`; etc.) but it seems like multiple items in the `mergeable[]` array which trigger on the same `when` event aren't getting the job done. This is what I have so far and would greatly appreciate any help:

```yaml
---
version: 2
mergeable:
  - when: issues.opened
    validate:
      - do: description
        must_include:
          regex: '(?<=### Kubernetes Platform\n\n)AKS'
    pass:
      - do: labels
        add: AKS
  - when: issues.opened
    validate:
      - do: description
        must_include:
          regex: '(?<=### Kubernetes Platform\n\n)GKE'
    pass:
      - do: labels
        add: GKE
```

**Comment by chipzoller** [comment]
After experimenting around with this some more, it seems like this manifest should and does work most of the time.

```yaml
version: 2
mergeable:
  - when: issues.opened
    name: Label validate
    validate:
      - do: description
        must_include:
          regex: '### Kyverno Rule Type\n\nValidate'
    pass:
      - do: labels
        add: validation

  - when: issues.opened
    name: Label mutate
    validate:
      - do: description
        must_include:
          regex: '### Kyverno Rule Type\n\nMutate'
```

The problem I'm seeing is Mergeable is sometimes not assigning a label, almost like certain issue open events get blackholed and it misses them. The result is some issues get labeled and some don't. The ones that get labeled are done correctly.

Is anyone else seeing this behavior?

**Comment by chipzoller** [comment]
@shine2lay do you have any idea of what might cause this? Is it a problem with the way the mergeable manifest is written or something external?

**Comment by shine2lay** [comment]
hey @chipzoller , 
I think you are missing the `pass` case for the second recipe, each recipe has it's own `pass` `fail` and `error` they don't share 
```
pass:
  - do: labels
    add: validation
```

**Comment by chipzoller** [comment]
Hey @shine2lay apologies, I did a fubar copy job. This is what I have:

```yaml
version: 2
mergeable:
  - when: issues.opened
    name: Label validate
    validate:
      - do: description
        must_include:
          regex: '### Kyverno Rule Type\n\nValidate'
    pass:
      - do: labels
        add: validation

  - when: issues.opened
    name: Label mutate
    validate:
      - do: description
        must_include:
          regex: '### Kyverno Rule Type\n\nMutate'
    pass:
      - do: labels
        add: mutation

  - when: issues.opened
    name: Label generate
    validate:
      - do: description
        must_include:
          regex: '### Kyverno Rule Type\n\nGenerate'
    pass:
      - do: labels
        add: generation

  - when: issues.opened
    name: Label imageVerify
    validate:
      - do: description
        must_include:
          regex: '### Kyverno Rule Type\n\nimageVerify'
    pass:
      - do: labels
        add: imageVerify
```

I'm still finding is that the labels are being applied inconsistently. I'll create an issue, it'll get labeled properly. I'll create another issue with the same string in the regex match and it won't. I don't understand what might cause this since the logic seems to work otherwise.
