### ISSUE TITLE
Support glob for "requires" in dependent rule?

### ISSUE THREAD

**Issue by andrewbihl** [mergeability/mergeable#628]
Are there any plans to support globs or regex in the files/require argument in the dependent rule?

Use case is:

```
 - do: dependent
        changed:
          file: '**/schemas/**/*.sql'
          required: ['**/schemas/**/Changelog.md']
        message: 'Update Changelog.md for schema changes'
```
