### ISSUE TITLE
Support issue_comment in filters

### ISSUE THREAD

**Issue by cuong-tech** [mergeability/mergeable#639]
Hi,

It would be useful if we could support `issue_comment` in filters:
https://github.com/mergeability/mergeable/blob/7d9efc55ba0d1d5f251aea8bc79a54e0e580a4e5/lib/filters/payload.js#L23-L30

The use case is developers can just add a comment `merge` to trigger the `merge` action
```
  - when: issue_comment.created
    name: 'Merge on comment'
    filter:
      - do: payload
        comment:
          body:
            must_include:
              regex: 'merge'
    validate: []
    pass:
      - do: merge
        merge_method: "rebase"
```

Is it just a matter of adding `issue_comment.*` to the `supportedEvents` array?

Thanks!
