### ISSUE TITLE
Internal error when using nested operators

### ISSUE THREAD

**Issue by PieterBunnenberg** [mergeability/mergeable#671]
I created a mergeable config to validate the PR size, but an approver from a specific team can overrule this PR size checks:
```
version: 2
mergeable:
  - when: pull_request.opened, pull_request.reopened, pull_request.synchronize
    name: pull-request lint
    validate:
      - do: or
        validate:
          - do: and
            validate:
              - do: size
                lines:
                  total:
                    count: 10000
                    message: Change is very large. Should be under 5000 lines of additions and deletions.
              - do: changeset
                max:
                count: 50
                message: You exceeded the maximum nubmber of modified/added files.
                files:
                  added: true
                  modified: true
                  deleted: false
          - do: approvals
            min:
              count: 1
              message: 'team-ci can overrule PR lint.'
            limit:
              teams: ['team-ci']
```

Sadly this causes a internal error:
> ❗ Validator: INTERNAL ERROR
> Status ERROR
> 
> ❗ Internal error!
> Input :
> Settings : {}
> Error : This is a mergeable bug, please report it on our issue tracker: https://github.com/mergeability/mergeable/issues/new
> ```
>TypeError: Cannot convert undefined or null to object
>    at Function.keys (<anonymous>)
>    at Changeset.validateSettings (/app/lib/validators/validator.js:80:30)
>    at Changeset.validateSettings (/app/lib/validators/validator.js:87:14)
>    at Changeset.processValidate (/app/lib/validators/validator.js:45:12)
>    at validateFuncCall (/app/lib/flex/lib/getValidatorPromises.js:4:74)
>    at /app/lib/flex/lib/createPromises.js:8:21
>    at Array.forEach (<anonymous>)
>    at createPromises (/app/lib/flex/lib/createPromises.js:3:18)
>    at getValidatorPromises (/app/lib/flex/lib/getValidatorPromises.js:6:10)
>    at andOrValidatorProcessor (/app/lib/validators/lib/andOrValidatorProcessor.js:43:20)
> ```

Can you give me some hints if this is an issue with my configuration or with mergeable.

Thank you very much.
