### ISSUE TITLE
request_review action not functional on an organizations repositories

### ISSUE THREAD

**Issue by stephanhirsch** [mergeability/mergeable#673]
we're trying to implement a simple action to add reviewers to a Pull Request with something like
```
- when: pull_request.*
  validate:
    - do: label
      must_include:
        regex: test-request-review
  pass:
    - do: request_review
      reviewers: ['reviewer1']
```
having ensured that `reviewer1` has access to the repositories in question.
We see different behavior on test repositories on user accounts and on organizations: while in all cases the validator passes successfully, the action `request_review` only is executed successfully on user accounts' repositories, but not on organizations' ones (while on the other hand `reviewer1` can be added manually as reviewer on the organizations'  repositories).

I checked the past issues here, but couldn't find an answer on that behavior. Also found no hint on that in the mergeable docs.
We run mergeable v2.12.1 currently.
