### ISSUE TITLE
Is it possible to hide the output of a successful validator?

### ISSUE THREAD

**Issue by andrewbihl** [mergeability/mergeable#693]
I thought the falling would _prevent_ any output showing up in the PR checks when successful:

```
  - when: pull_request.*
    name: 'PR description filled out'
    validate:
      - do: description
        must_exclude:
          regex: 'Please explain what the point of this work was.'
    fail:
      - do: checks
        status: 'action_required'
        payload:
          summary: Please fill out the PR description.
```

It did not. Is it possible to prevent unnecessary message showing up in the PR checks? 

Yaml has version: 2

**Comment by andekande** [comment]
you would need to add
```
    pass:
      - do: checks
        status: 'success'
        name: ''
        payload:
          title: ''
          summary: ''
```
