### ISSUE TITLE
[BUG] - Getting an error for a specific PR

### ISSUE THREAD

**Issue by oferprtz-atbay** [mergeability/mergeable#711]
Hey,

Using mergeable for specific repo and all PR's are working correctly.
today ive created new PR with just helm files changes and got this error from mergeable:
```
Error Details
HttpError: Invalid request.

No subschema in "anyOf" matched.
For 'anyOf/0', {"labels"=>{"labels"=>["Ready for Review"]}} is not an array.
For 'anyOf/1', {"labels"=>{"labels"=>["Ready for Review"]}} is not an array.
For 'properties/labels', {"labels"=>["Ready for Review"]} is not an array.
```

on the checks tab im getting this:
![image](https://user-images.githubusercontent.com/125448935/235739388-50a2fe8e-49ac-4a5e-8a67-ac6df23f5124.png)

Didnt change mergeable yaml for a while now.

thanks,
Ofer

**Comment by oferprtz-atbay** [comment]
Hey @shine2lay thanks for the quick reply.
when creating the PR the mergeable start to run and post this:
![image](https://user-images.githubusercontent.com/125448935/235858051-07cb44ec-132a-449e-81d7-d02f3d6bf9e2.png)

expected result:
![image](https://user-images.githubusercontent.com/125448935/235858177-087f67e9-c74d-473f-b6e2-fc7e2816c349.png)

not sure why its happening, the mergeable config runs on all other repos smoothly.
here is the config:
`version: 2
mergeable:
  - when: schedule.repository
    validate:
      - do: stale
        days: 30
        type: pull_request
    pass:
      - do: comment
        payload:
          body: This PR is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 10 days.
      - do: labels
        add: 'Stale'
          
  - when: pull_request.*
    validate:          
      - do: description
        no_empty:
          enabled: true
          message: Description matter and should not be empty. Provide detail with **what** was changed, **why** it was changed, and **how** it was changed.
      - do: or
        validate:
          - do: title
            must_include:
              regex: '\[(DEVO|RND|CP|DP|DS|CR)-\d+\]|\[SRE\]|\[DEVOPS\]'          
    pass:
      - do: labels
        add: 'Ready for Review'
      - do: checks
        status: 'success'`

**Comment by shine2lay** [comment]
I have never seen this before, any chance the this could be complaining about the label not existing?

**Comment by oferprtz-atbay** [comment]
In our configuration (as you can see above) we are tagging success rules with "ready for review", nothing fancy here.
probably its fails when creating the label.
seems that the mergeable code has been change lately, i havent change our code in couple of months now.

**Comment by shine2lay** [comment]
There were few changes in the last couple months and none of them touches `labels` IIRC. so it's hard to imagine that the new codes have caused this

**Comment by DpoBoceka** [comment]
This is the config I use in a monorepo with **libs**, [backend] **services** and a **frontend**:

```
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: Add automerge label
    filter:
      - do: payload
        pull_request:
          draft:
            boolean:
              match: false
    validate:
      - do: and
        validate:
          - do: label
            must_exclude:
              regex: "^automerge$"
          - do: changeset
            must_exclude:
              regex:
                - "^frontend*"
    pass:
      - do: labels
        add: "automerge"

  - when: pull_request.*, pull_request_review.*
    name: Remove automerge label
    filter:
      - do: payload
        pull_request:
          draft:
            boolean:
              match: true
    validate:
      - do: label
        must_exclude:
          regex: "^automerge$"
    fail:
      - do: labels
        delete: "automerge"

  - when: pull_request.*, pull_request_review.*
    name: Set no-automerge label
    validate:
      - do: changeset
        begins_with:
          match:
            [
              "services/service1/",
              "services/service2/",
            ]
    pass:
      - do: labels
        add: "no-automerge"

  - when: pull_request.*, pull_request_review.*
    name: Set 2-reviews label
    validate:
      - do: changeset
        begins_with:
          match:
            [
              "services/service3/",
              "frontend/",
              "libs/lib1/",
            ]
    pass:
      - do: labels
        add: "2-reviews"

  - when: pull_request.*, pull_request_review.*
    name: Set frontend label
    validate:
      - do: changeset
        begins_with:
          match: ["frontend/"]
    pass:
      - do: labels
        add: "frontend"

  - when: pull_request.*, pull_request_review.*
    name: Approval check
    validate:
      - do: or
        validate:
          - do: and
            validate:
              - do: label
                must_include:
                  regex: "^2-reviews$"
              - do: approvals
                min:
                  count: 2
          - do: and
            validate:
              - do: label
                must_exclude:
                  regex: "^2-reviews$"
              - do: approvals
                min:
                  count: 1
    fail:
      - do: checks
        status: "failure"
        payload:
          title: "Mergeable Run have been Completed!"
          summary: |
            ### Status: {{toUpperCase validationStatus}}
                  Here are some stats of the run:
                  {{validationCount}} validations were ran.
                  {{passCount}} PASSED
                  {{failCount}} FAILED
          text: "{{#each validationSuites}}\n
            #### {{{statusIcon status}}} Validator: {{toUpperCase name}}\n
            {{#each validations }} * {{{statusIcon status}}} ***{{{ description }}}***\n
            Input : {{{details.input}}}\n
            Settings : {{{displaySettings details.settings}}}\n
            {{/each}}\n
            {{/each}}"
    pass:
      - do: checks
        status: "success"
        payload:
          title: "Mergeable Run have been Completed!"
          summary: "All the validators have returned 'pass'! \n Here are some stats of the run: \n {{validationCount}} validations were ran"
```
and PRs that change **frontend/*** are getting these now:

```
HttpError: Invalid request.

No subschema in "anyOf" matched.
For 'anyOf/0', {"labels"=>{"labels"=>["2-reviews", "frontend", "frontend"]}} is not an array.
For 'anyOf/1', {"labels"=>{"labels"=>["2-reviews", "frontend", "frontend"]}} is not an array.
For 'properties/labels', {"labels"=>["2-reviews", "frontend", "frontend"]} is not an array.

```

Would that help?
