### ISSUE TITLE
Pull request title checks are always case insensitive 

### ISSUE THREAD

**Issue by RapGeneral** [mergeability/mergeable#720]
I have the following configuration:
```
mergeable:
  - when: pull_request.*
    validate:
      - do: title
        must_include:
          regex: \[(Patch|Minor|Major|No-Version)\]
          message: "Please ensure the title is prefixed with a SemVer identifier in PascalCase ([Major], [Minor], [Patch] or [No-Version])"
```

Expected: Only PRs which contains pascal case SemVer identifiers will pass
Actual: All casings pass.

I looks trough the docs and couldnt find any way to configure the casing.
