### ISSUE TITLE
Mergeable failing to request PR reviews and post messages

### ISSUE THREAD

**Issue by DanielTsiang** [mergeability/mergeable#724]
Recently over the past few months I've noticed that Mergeable fails to request pull request reviews from GitHub teams, and also fails to post messages on pull requests.

It was working last year, I haven't changed any of the mergeable.yaml config but it's stopped working for some reason.

**Comment by shine2lay** [comment]
@DanielTsiang does it happen sporadically or all the time?

**Comment by DanielTsiang** [comment]
@shine2lay it hasn't been working all the time for a while now.

Here is a snippet of the relevant part of the `mergeable.yml` config to help with debugging it failing to post comments on pull requests:
```
version: 2  
mergeable:
  - when: pull_request.opened, pull_request.edited, pull_request.reopened, pull_request.ready_for_review
    filter:
      - do: payload
        pull_request:
          draft:
            boolean:
              match: false
    validate:
      - do: changeset
        must_include:
          regex: '^(dir-1)\/(?<service>service-1|service-2|service-3)\/(\k<service>)(\.env)$'
        files:
          added: true
          modified: true
          deleted: true
    pass:
      - do: comment
        payload:
          body: >
            The relevant team will need to control merging this PR.
            
            @relevant-team: please review this PR.

```
