### ISSUE TITLE
Regex fails to process while searching for presence of multiple string

### ISSUE THREAD

**Issue by lbonilla68** [mergeability/mergeable#726]
Hello,

I'm using the following config and mergeable errors our while processing the regex. The regex works fine for me in my regex validator.

```
version: 2
mergeable:
  - when: pull_request.*
    filter:
      - do: repository
        name:
          must_exclude:
            regex: my-repo
      - do: author
        must_exclude:
          regex: dependabot[bot]
    validate:
      - do: description
        and:
          - no_empty:
              enabled: true
              message: Please provide a description 
          - or:
            - and:
              - must_include:
                  regex: '^(?s)(?!(.*\[x]){2}).*\[x]'
                  regex_flag: none
                  message: Only 1 checkbox must be checked to dicate if it's a Patch, Minor or Major change.
```
This ensures that only a single item is checked in the description after opening a PR. It should fail if more than 2 checkboxes are checked. 

### Only Check One
- [] Patch 
- [] Minor
- [] Major

Here is a link to my Regex validation
[](https://regex101.com/r/NkrHhq/1)
