### ISSUE TITLE
supportedSettings[key].includes is not a function

### ISSUE THREAD

**Issue by Paddy-Farmeye** [mergeability/mergeable#729]
Hi there I'm getting the error below with the following config:
```
version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: or
        validate:
          - do: title
            must_include:
              regex: ^\[FE+-\d+\]*
              message: FARMEYE commits should be of the form "[FE-###] A brief description of the feature/bug".
          - do: title
            begins_with: 'Release'
```
Error:
```
❗ Validator: INTERNAL ERROR
Status ERROR

❗ Internal error!
Input :
Settings : {}
Error : This is a mergeable bug, please report it on our issue tracker: https://github.com/mergeability/mergeable/issues/new
TypeError: supportedSettings[key].includes is not a function
    at Title.validateSettings (/app/lib/validators/validator.js:89:42)
    at Title.processValidate (/app/lib/validators/validator.js:46:12)
    at validateFuncCall (/app/lib/flex/lib/getValidatorPromises.js:4:74)
    at /app/lib/flex/lib/createPromises.js:8:21
    at Array.forEach (<anonymous>)
    at createPromises (/app/lib/flex/lib/createPromises.js:3:18)
    at getValidatorPromises (/app/lib/flex/lib/getValidatorPromises.js:6:10)
    at logicalConnectiveValidatorProcessor (/app/lib/validators/lib/logicalConnectiveValidatorProcessor.js:43:20)
    at Or.validate (/app/lib/validators/or.js:17:12)
    at Or.processValidate (/app/lib/validators/validator.js:57:17)
```
Basically, it should pass if the title beginsWith 'Release' or matches the regex ... I've potentially misconfigured. Hopefully you can help, thanks.
