### ISSUE TITLE
Seemingly simple checks take minutes to complete or even completely hang

### ISSUE THREAD

**Issue by adamshortev** [mergeability/mergeable#740]
We're using the following configuration:

```
version: 2
mergeable:
  - when: pull_request.*
    name: PR Label Check
    validate:
      - do: label
        must_exclude:
          regex: 'wip|status\: do not merge'
    pass:
      - do: checks
        status: 'success'
        payload:
          title: 'PR Label Check - Pass'
          summary: 'PR labels pass'
    fail:
      - do: checks
        status: 'failure'
        payload:
          title: 'PR Label Check - Fail'
          summary: 'Cannot merge with current labels'

  - when: pull_request.*
    name: PR Title Check
    validate:
      - do: title
        or:
          - must_include:
              regex: '^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(\S+\))?: .+'
              message: 'PR title does not follow Conventional Commits (e.g., "feat(scope): add new feature").'
          - must_include:
              regex: '^RELEASE \d{4}\.\d{1,2}\.\d{1,2}$'
              message: 'PR title is not a release title (e.g. RELEASE 2024.1.1).'
    pass:
      - do: checks
        status: 'success'
        payload:
          title: 'PR Title Check - Pass'
          summary: 'Your PR title follows the Conventional Commits specification.'
    fail:
      - do: checks
        status: 'failure'
        payload:
          title: 'PR Title Check - Fail'
          summary: 'Please ensure your PR title follows the Conventional Commits specification.'

```

We're seeing the individual mergeable actions take an age to finish, sometimes as much as 7 minutes, sometimes they appear to hang indefinitely. It's gotten to the point we've made the mergeable checks non-required now as it was blocking us too much.

Is there a misconfiguration here somewhere?
