### ISSUE TITLE
No Config file found

### ISSUE THREAD

**Issue by raghunandannm** [mergeability/mergeable#757]
We are planning to integrate mergeable in our github repo. As part of this we have created a .github/mergeable.yml file in a feature branch and the mergeable has got triggered as exepcted.

Later on, when we tried to create a new branch from this feature branch the mergeable is not getting triggered and showing up "No Config file found" error. Now, when we touch this mergeable.yml file in this feature branch, then mergeable is getting triggered.

Is there any reason for this? Should mergeable.yml file be available on main/develop branch to get triggered automatically? Or should we have to touch this mergeable.yml file in every PR?

**Comment by andekande** [comment]
It is intended to have only one mergeable.yaml in the main branch.
If you have conventions for naming additional branches, like 'fix-the-unknown' then you can formulate a rule that only triggers for a specific prefix of a branch, like:
```yaml
validate:
  - do: baseRef
    must_include:
       regex: '^fix'
  - do: description
        no_empty:
          enabled: true
          message: Description is required for Fixes 
```
