### ISSUE TITLE
Mergeable errors then closed an opened issue

### ISSUE THREAD

**Issue by paulbalandan** [mergeability/mergeable#778]
## Error Encountered
```
❌ Error Occurred while executing an Action

If you believe this is an unexpected error, please report it on our issue tracker: https://github.com/mergeability/mergeable/issues/new

Error Details

TypeError: Cannot read property 'replace' of undefined
```

## Config
```yaml
version: 2
mergeable:
  - when: issues.opened
    validate:
      - do: description
        and:
          - must_include:
              regex: '^### PHP Version'
          - must_include:
              regex: '^### CodeIgniter4 Version'
      - do: author
        and:
          - must_exclude:
              regex: 'kenjis'
          - must_exclude:
              regex: 'lonnieezell'
          - must_exclude:
              regex: 'MGatner'
          - must_exclude:
              regex: 'michalsn'
          - must_exclude:
              regex: 'paulbalandan'
          - must_exclude:
              regex: 'samsonasik'
    fail:
      - do: comment
        payload: |
          Hi there! :wave:

          It looks like you opened an issue without following the bug report template:

          Bug report ([open an issue](https://github.com/codeigniter4/CodeIgniter4/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml&title=Bug%3A+))

          If you are opening a feature request or support question, please do so in the [forums](https://forum.codeigniter.com/forum-30.html).

          The current issue will be closed. This is a precaution to save maintainers' time, I hope you'll understand.

          Sincerely, the mergeable bot 🤖
      - do: close
```

Basically, the rule checks if the opened issues follow the bug report template. If it does not, it will fail with the comment message then close the issue. However, the maintainers listed in the authors are exempted from the rule as they use the other template for dev purposes.
