### ISSUE TITLE
filter does not work?

### ISSUE THREAD

**Issue by darliiin** [mergeability/mergeable#779]
**The filter does not work**
I am trying to disable the launch of the validator, in the case when the author of the PR is a specific user

**Here is my `mergeable.yml`:**
```
version: 2
mergeable:
  # CHANGELOG.md is required in the PR, unless it's from 'darliiin'
  - when: pull_request.*
    name: 'Checking for the presence of the CHANGELOG.md file'
    filter:
      - do: author
        must_exclude:
            regex: '^darliiin$'
            message: 'Skipping CHANGELOG.md check for darliiin PRs'
    validate:
      - do: changeset
        no_empty:
          enabled: true
          message: 'empty'
        must_include:
          regex: 'CHANGELOG.md'
          message: 'CHANGELOG.md with details must be present in every PR'

```
I want the `CHANGELOG.md` file not to be checked for a specific user
But with my `mergeable.yml` I still see the verification status failed

![Image](https://github.com/user-attachments/assets/6ea3249e-3867-41b5-9f04-1117f47487f8)
